services:
  - type: web
    name: frogjump-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.2"
    autoDeploy: true